server:
  port: 8072
spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    httpclient:
      connect-timeout: 1000
      response-timeout: 10s

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewaysarver"
    description: "Bank Gateway Server Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      bogdan:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


#Patterns examples
#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 10
#      permittedNumberOfCallsInHalfOpenState: 2
#      failureRateThreshold: 50
#      waitDurationInOpenState: 10000
#
#resilience4j.retry:
#  configs:
#    default:
#      maxAttempts: 3
#      waitDuration: 500
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
#      ignoreExceptions:
#        - java.lang.NullPointerException
#      retryExceptions:
#        - java.util.concurrent.TimeoutException
#
#resilience4j.ratelimiter:
#  configs:
#    default:
#      timeoutDuration: 1000
#      limitRefreshPeriod: 5000
#      limitForPeriod: 1