server:
  port: 8072
spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewaysarver"
    description: "Bank Gateway Server Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      bogdan:
        gatewayserver: DEBUG