spring:
  application:
    name: "config_server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bbogdasha/spring-cloud-configs.git"
          search-paths: microservices-bank-api
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

server:
  port: 8071
